djangoProject/urls.py
from django.contrib import admin
from django.urls import path

from school.views import create, student, account, teacher, room, course, chart, temp

urlpatterns = [
    # 后台管理员
    path('admin/', admin.site.urls),
    # 调试
    path('create/table/', create.create_table),

    # 查看学生信息
    path('stu/list/', student.stu_list),
    # 查看上课学生信息
    path('course/now/<int:tp_id>/list/', student.stu_in_class_list),
    # 查看历史课程信息
    path('course/previous/<int:tp_id>/list/', student.stu_in_previous_class_list),
    # 添加学生信息
    path('stu/add/', student.stu_add),
    # 删除学生信息
    path('stu/delete/', student.stu_delete),
    # 修改学生信息
    path('stu/<int:stu_id>/edit/', student.stu_edit),
    # 查看学生成绩
    path('stu/grade/',student.query_grade),

    # 查看教师信息
    path('teach/list/', teacher.teach_list),
    # 添加教师信息
    path('teach/add/', teacher.teach_add),
    # 删除教师信息
    path('teach/delete/', teacher.teach_delete),
    # 修改教师信息
    path('teach/<int:teach_id>/edit/', teacher.teach_edit),

    # 查看教室信息
    path('room/list/', room.room_list),
    # 添加教室信息
    path('room/add/', room.room_add),
    # 删除教室信息
    path('room/delete/', room.room_delete),
    # 修改教室信息
    path('room/<int:room_id>/edit/', room.room_edit),

    # 查看全部课程信息
    path('course/list/', course.course_list),
    # 查看教师当前学期课程信息
    path('teach/course/list/', course.show_teach_time_table),
    # 查看教师历史学期课程信息
    path('teach/course/previous/list/', course.previous_teaching_course_list),
    # 查看学生当前学期课程信息
    path('stu/course/list/', course.show_stu_time_table),
    # 添加课程信息
    path('course/add/', course.course_add),
    # 删除课程信息
    path('course/delete/', course.course_delete),

    # 课程分析
    path('manager/chart/list/', chart.manager_analysis_achievement),
    path('teach/chart/list/', chart.teach_analysis_achievement),
    path('chart/bar/', chart.char_bar),

    # 排课
    path('scheduling/course/', course.arranging_course),

    # 选课
    path('select/course/', course.select_course),

    # 登录
    path('',account.sign_in),
    path('login/', account.sign_in),
    path('logout/', account.sign_out),

    # 修改密码
    path('modify/pwd/', account.get_modify_pwd_page),
    path('modify/password/', account.modify_password),

    # 录入成绩
    path('score/<int:tp_id>/record/', course.score_record),

]

school/models.py
from django.db import models

# 引用内置的user模型
from django.contrib.auth.models import AbstractUser


class Student(models.Model):
    """学生信息表"""

    gender_choice = (
        (1, "男"),
        (2, "女")
    )

    user = models.ForeignKey(to='User', verbose_name="学号", on_delete=models.CASCADE)
    name = models.CharField(verbose_name="姓名", max_length=10)
    gender = models.CharField(verbose_name="性别", max_length=1, choices=gender_choice)
    born_date = models.DateField(verbose_name="出生日期")
    enrollment_date = models.DateField(verbose_name="入学日期")
    majorId= models.IntegerField(verbose_name="专业id", max_length=8)
    classId = models.IntegerField(verbose_name="班级id", max_length=8)

    def __str__(self):
        return self.name + " " + self.major_name + " " + self.class_name


class Teacher(models.Model):
    """教师信息表"""

    gender_choice = (
        (1, "男"),
        (2, "女")
    )

    title_choice = (
        (1, "助教"),
        (2, "讲师"),
        (3, "副教授"),
        (4, "教授"),
    )

    user = models.ForeignKey(to='User', verbose_name="工号", max_length=7, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="姓名", max_length=10)
    born_date = models.DateField(verbose_name="出生日期")
    entry_date = models.DateField(verbose_name="入职日期")
    title = models.CharField(verbose_name="职称", max_length=8, choices=title_choice, default=2)
    collegeId = models.ForeignKey(verbose_name="学院id", max_length=8)
    gender = models.CharField(verbose_name="性别", max_length=1, choices=gender_choice)

    def __str__(self):
        return self.name


class Course(models.Model):
    """课程信息表"""

    category_choice = (
        (1, "必修"),
        (2, "选修")
    )

    user = models.ForeignKey(to='Course', verbose_name="课程号", max_length=8, on_delete=models.CASCADE)
    course_name = models.CharField(verbose_name="课程名", max_length=10)
    score = models.SmallIntegerField(verbose_name="学分", max_length=2, decimal_places=1)
    the_period = models.SmallIntegerField(verbose_name="理论课学时", max_length=2, default=0)
    exp_period = models.SmallIntegerField(verbose_name="实验课学时", max_length=2, default=0)
    category = models.CharField(verbose_name="课程性质", max_length=1, choices=category_choice)

    def __str__(self):
        return self.course_name + "(" + self.get_category_display() + ")"


class ClassRoom(models.Model):
    """教室表"""
    class_number = models.CharField(verbose_name="教室号", max_length=8)
    spot = models.CharField(verbose_name="地点", max_length=10)
    volume = models.IntegerField(verbose_name="容纳人数", max_length=8)
    academyId = models.ForeignKey(to='academy', on_delete=models.CASCADE, verbose_name='学院Id')


class Academy(models.Model):
    """学院表"""
    major_name = models.CharField(verbose_name="学院名", max_length=20)


class Major(models.Model):
    """专业表"""
    major_name = models.CharField(verbose_name="专业名", max_length=20)
    academyId = models.ForeignKey(verbose_name="学院id", max_length=8)


class SchoolClass(models.Model):
    """班级表"""
    class_name = models.CharField(verbose_name="班级名", max_length=20)
    grade = models.CharField(verbose_name="年级", max_length=4)

    def __str__(self):
        return self.student.name + '：' + self.teaching_program.course.course_name


class Time(models.Model):
    """时间表"""
    week = models.CharField(verbose_name="周次", max_length=4)
    day = models.CharField(verbose_name="星期", max_length=4)
    lesson = models.CharField(verbose_name="节次", max_length=4)

    def __str__(self):
        return self.week + ' ' + self.day + ' ' + self.lesson


class TeachingProgram(models.Model):
    """教学计划表"""

    course = models.ForeignKey(to='Course', verbose_name='课程id', on_delete=models.CASCADE)
    teacherId = models.ForeignKey(to='Teacher', verbose_name='教师id', max_length=8, on_delete=models.CASCADE)
    classesId = models.ForeignKey(verbose_name='班级id', max_length=8, on_delete=models.CASCA)
    openTime = models.CharField(verbose_name='开设学期', max_length=1)
    the_start_week = models.CharField(verbose_name='理论课开始周次', max_length=4, null=True, blank=True)
    the_end_week = models.CharField(verbose_name='理论课结束周次', max_length=4, null=True, blank=True)
    exp_start_week = models.CharField(verbose_name='实验课开始周次', max_length=4, null=True, blank=True)
    exp_end_week = models.CharField(verbose_name='实验课结束周次', max_length=4, null=True, blank=True)

    def __str__(self):
        return self.course.course_name + ' ' + self.teacher.name + ' ' + self.classes


class RoomTime(models.Model):
    """教室时间表"""
    roomId = models.ForeignKey(verbose_name="教室id", max_length=8, unique=True)
    timeId = models.ForeignKey(verbose_name="时间id", max_length=8)

    def __str__(self):
        return self.room_name


class SelectCourse(models.Model):
    """选课表"""

    studentId = models.ForeignKey(to='Student', max_length=8, on_delete=models.CASCADE, verbose_name='学生id')
    teaching_programId = models.ForeignKey(to='TeachingProgram', max_length=8, on_delete=models.CASCADE, verbose_name='教学计划id', null=True,
                                         blank=True)
    gradeId = models.IntegerField(verbose_name='成绩id', max_length=8, null=True, blank=True)

    def __str__(self):
        return self.student.name + '：' + self.teaching_program.course.course_name


class CourseArrangement(models.Model):
    """课程安排表"""
    type_choic = (
        (1, '理论课'),
        (2, '实验课')
    )

    teaching_programID = models.ForeignKey(to='TeachingProgram', max_length=8, verbose_name='教学计划id', on_delete=models.CASCADE)
    roomTimeId = models.ForeignKey(to='Room', verbose_name='教室时间id', max_length=8, on_delete=models.CASCADE)
    tmp_volume = models.IntegerField(verbose_name='当前人数', max_length=8, default=0)

    def __str__(self):
        return self.teaching_program.course.course_name + " " + self.room.room_name + self.time.__str__()


# class Message(models.Model):
#     """消息表"""
#
#     message_id = models.CharField(max_length=20, verbose_name='消息号', primary_key=True, unique=True, db_index=True)
#     student_id = models.ForeignKey(Student, on_delete=models.DO_NOTHING, verbose_name='学号')
#     message_content = models.CharField(max_length=1000, verbose_name='消息内容')
#     message_send_time = models.DateTimeField(auto_now_add=True, verbose_name='发送日期')
#     message_status = models.CharField(max_length=20, verbose_name='消息状态')
#     message_title = models.CharField(max_length=255, verbose_name='消息标题')

school/views/account.py
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django import forms
from school.utils import bootstrap
from school import models


class LoginForm(bootstrap.BootStrapForm):
    username = forms.CharField(label='用户名', widget=forms.TextInput, required=True)
    password = forms.CharField(label='密码', widget=forms.PasswordInput(render_value=True), required=True)


def sign_in(request):
    if request.user.is_authenticated:
        identify = request.user.identify
        if identify == 1:
            return redirect('/stu/list/')
        elif identify == 2:
            return redirect('/course/list2/')
        else:
            return redirect('/course/list3/')
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})
    else:
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if not user:
                form.add_error('password', '用户名或密码错误')
                return render(request, 'login.html', {'form': form})
            login(request, user)
            if user.identify == 1:  # 教务人员
                request.session['name'] = models.Teacher.objects.filter(user__username=username).first().name
                return redirect('/stu/list/')
            elif user.identify == 2:  # 教师
                request.session['name'] = models.Teacher.objects.filter(user__username=username).first().name
                return redirect('/course/list2/')
            else:  # 学生
                request.session['name'] = models.Student.objects.filter(user__username=username).first().name
                return redirect('/course/list3/')

        else:
            return render(request, 'login.html', {'form': form})


def sign_out(request):
    user = request.user
    if user.is_authenticated:
        logout(request)
    return redirect('/login/')


def get_modify_pwd_page(request):
    identify = request.user.identify
    if identify == 1:
        return render(request, 'manager_modify_pwd.html')
    elif identify == 2:
        return render(request, 'teacher_modify_pwd.html')
    else:
        return render(request, 'student_modify_pwd.html')


def modify_password(request):
    now_password = request.GET.get('now_password')
    if not request.user.check_password(now_password):
        return JsonResponse({
            'status': False,
        })
    new_password = request.GET.get('new_password')
    request.user.set_password(new_password)
    request.user.save()
    return JsonResponse({
        'status': True,
    })

school/views/chart.py
from django.shortcuts import render
from django.http import JsonResponse
from school import models
from chart_implement import ManagerCharInfoService, TeachCharInfoService, ShowChartInfoService

from datetime import datetime


class CharBar:
    def __init__(self, cls):
        self.cls = cls

    def show_chart_info(self):
        return self.cls.show_chart_info()


class AnalysisAchievementForManager:
    def __init__(self, cls):
        self.cls = cls

    def analysis_achievement(self):
        return self.cls.manager_analysis_achievement()


class AnalysisAchievementForTeacher:
    def __init__(self, cls):
        self.cls = cls

    def analysis_achievement(self):
        return self.cls.teach_analysis_achievement()


def manager_analysis_achievement(request):
    """教务人员课程分析"""
    manager_analysis_achievement = ManagerCharInfoService(request)
    drive = AnalysisAchievementForManager(manager_analysis_achievement)
    return drive.analysis_achievement()


def teach_analysis_achievement(request):
    """教师课程分析"""
    teach_analysis_achievement = TeachCharInfoService(request)
    drive = AnalysisAchievementForTeacher(teach_analysis_achievement)
    return drive.analysis_achievement()


def char_bar(request):
    """构造柱状图数据"""
    show_chart_info_service = ShowChartInfoService(request)
    drive = CharBar(show_chart_info_service)
    return drive.show_chart_info()

school/views/chart_Interface.py
from abc import ABC, abstractmethod


class IManagerAnalysisAchievementService(ABC):
    @abstractmethod
    def manager_analysis_achievement(self):
        pass


class ITeachAnalysisAchievementService(ABC):
    @abstractmethod
    def teach_analysis_achievement(self):
        pass


class IShowAnalysisInfo(ABC):
    @abstractmethod
    def show_analysis_info(self):
        pass

school/views/course_Interface.py
from abc import ABC, abstractmethod


class IShowCourseInfoService(ABC):
    @abstractmethod
    def show_course_info(self):
        pass


class IAddCourseService(ABC):
    @abstractmethod
    def course_add(self):
        pass


class IDeleteCourseService(ABC):
    @abstractmethod
    def course_delete(self):
        pass


class IArrangingCourseService(ABC):
    @abstractmethod
    def arranging_course(self):
        pass


class ISelectCourseService(ABC):
    @abstractmethod
    def select_course(self):
        pass


class IShowTeachTimeTableService(ABC):
    @abstractmethod
    def show_teach_time_table(self):
        pass


class IShowPreviousTeachingCourseInfoService(ABC):
    @abstractmethod
    def show_previous_teaching_course_info(self):
        pass


class IRecordScoreService(ABC):
    @abstractmethod
    def score_record(self, tp_id):
        pass


class IShowStuTimeTableService(ABC):
    @abstractmethod
    def show_stu_time_table(self):
        pass

school/views/room.py
from django import forms
from django.core.exceptions import ValidationError
from django.http import JsonResponse

from django.shortcuts import render, redirect

from school import models
from school.utils import pagination, bootstrap
from school.views.create import create_stu_id
from django.contrib.auth.decorators import login_required

from room_implement import ShowRoomInfoService, AddRoomService, DeleteRoomService, EditRoomService


class AddRoomForm(bootstrap.BootStrapForm):
    building_name = forms.CharField(label='楼名')
    room_number = forms.CharField(label='教室号')
    department = forms.CharField(label="系")
    volume = forms.IntegerField(label="容量")

    def clean_building_name(self):
        building_name = self.cleaned_data['building_name']
        if not models.Room.objects.filter(room_name__contains=building_name):
            raise ValidationError('请输入正确的楼名。')
        return building_name

    def clean_room_number(self):
        building_name = self.cleaned_data['building_name']
        room_number = self.cleaned_data['room_number']
        room_name = building_name + '-' + room_number
        if models.Room.objects.filter(room_name=room_name):
            raise ValidationError('该教室记录已存在。')
        return room_number

    def clean_department(self):
        department = self.cleaned_data['department']
        print(department)
        if not models.Student.objects.filter(department_name=department):
            raise ValidationError('输入的系不存在。')
        return department

    def clean_volume(self):
        volume = self.cleaned_data['volume']
        if volume <= 0:
            raise ValidationError('请输入正确的教室容量。')
        return volume


class EditRoomForm(bootstrap.BootStrapForm):
    building_name = forms.CharField(label='楼名', widget=forms.TextInput(attrs={'readonly': True}))
    room_number = forms.CharField(label='教室号', widget=forms.TextInput(attrs={'readonly': True}))
    department = forms.CharField(label="系")
    volume = forms.IntegerField(label="容量", widget=forms.TextInput(attrs={'readonly': True}))

    def clean_department(self):
        department = self.cleaned_data['department']
        print(department)
        if not models.Student.objects.filter(department_name=department):
            raise ValidationError('输入的系不存在。')
        return department


class ShowRoomInfo:
    def __init__(self, cls):
        self.cls = cls

    def show_room_info(self):
        self.cls.show_room_info()


class AddRoom:
    def __init__(self, cls):
        self.cls = cls

    def room_add(self):
        self.cls.room_add()


class DeleteRoom:
    def __init__(self, cls):
        self.cls = cls

    def room_delete(self):
        self.cls.room_delete()


class EditRoom:
    def __init__(self, cls):
        self.cls = cls

    def room_edit(self, room_id):
        self.cls.room_edit(room_id)


@login_required
def room_list(request):
    show_room_info_service = ShowRoomInfoService(request)
    drive = ShowRoomInfo(show_room_info_service)
    return drive.show_room_info()


@login_required
def room_add(request):
    room_add_service = AddRoomService(request)
    drive = AddRoom(room_add_service)
    return drive.room_add()


@login_required
def room_delete(request):
    room_delete_service = DeleteRoomService(request)
    drive = DeleteRoom(room_delete_service)
    return drive.room_delete()


@login_required
def room_edit(request, room_id):
    room_edit_service = EditRoomService(request)
    drive = EditRoom(room_edit_service)
    return drive.room_edit(room_id)

school/templates/course_add.html
{% extends 'manager_layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker-master/css/bootstrap-datepicker.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><strong>添加课程安排</strong></h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in courseForm %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}


                    <button type="submit" class="btn btn-primary"> 提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker-master/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker-master/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>

    <script>
        $(function () {
            $('#id_born_date, #id_enrollment_date').datepicker({
                format: 'yyyy-mm-dd',
                language: "zh-CN",
                todayHighlight: true,
                autoclose: true
            });
        })
    </script>
{% endblock %}

school/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="len" style="background-image: url('{% static 'img/background.png' %}');padding: 1.1em;min-height: 95vh;">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'img/background.png' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body style="background-image: url('{% static 'img/background.png' %}');padding: 1.1em;min-height: 95vh;">
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <input type="submit" value="登 录" class="btn btn-primary">
    </form>
</div>

</body>
</html>

school/templates/room_add.html
{% extends 'manager_layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker-master/css/bootstrap-datepicker.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><strong>添加教室</strong></h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in roomForm %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}


                    <button type="submit" class="btn btn-primary"> 提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker-master/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker-master/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>

    <script>
        $(function () {
            $('#id_born_date, #id_enrollment_date').datepicker({
                format: 'yyyy-mm-dd',
                language: "zh-CN",
                todayHighlight: true,
                autoclose: true
            });
        })
    </script>
{% endblock %}

school/templates/student_show.html
{% extends 'manager_layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/stu/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                添加学生
            </a>

            <div style="float: right;width: 300px;">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="value" class="form-control" placeholder="请输入学号 / 姓名..."
                               value={{ value }}>
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                      </span>
                    </div>
                </form>
            </div>

        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                学生列表
            </div>
            <!-- Table -->
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>学号</th>
                    <th>姓名</th>
                    <th>性别</th>
                    <th>系</th>
                    <th>专业</th>
                    <th>班级</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for student in students %}
                    <tr>
                        <th>{{ student.user.username }}</th>
                        <td>{{ student.name }}</td>
                        <td>{{ student.get_gender_display }}</td>
                        <td>{{ student.department_name }}</td>
                        <td>{{ student.major_name }}</td>
                        <td>{{ student.class_name }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/stu/{{ student.user.username }}/edit/">编辑</a>
                            <input uid="{{ student.user.username }}" class="btn btn-danger btn-xs btn-delete" type="button" value="删除">
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <ul class="pagination">
            {{ page_string }}
        </ul>
    </div>

    <!-- 删除(对话框) -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <h4>是否确认删除？</h4>
                <p style="margin: 10px 0;">删除后，所有关联的数据也会一并删除，无法复原。</p>
                <p style="text-align: right;">
                    <button id="btnConfirmDelete" type="button" class="btn btn-danger">删 除</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">不，再想想</button>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        let DELETE_ID;
        $(function () {
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
        })

        function bindBtnDeleteEvent() {
            $(".btn-delete").click(function () {
                $("#deleteModal").modal('show');
                DELETE_ID = $(this).attr("uid");
            });
        }

        function bindBtnConfirmDeleteEvent(){
            $("#btnConfirmDelete").click(function () {
                $.ajax({
                    url: "/stu/delete/",
                    type: "GET",
                    data: {
                      uid: DELETE_ID,
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if(res.status) {
                            $("#deleteModal").modal('hide');
                            DELETE_ID = 0;
                            location.reload();
                        }

                    }
                })
            });
        }
    </script>
{% endblock %}

school/templates/teacher_add.html
{% extends 'manager_layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker-master/css/bootstrap-datepicker.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><strong>添加教师</strong></h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in teachForm %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}


                    <button type="submit" class="btn btn-primary"> 提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker-master/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker-master/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>

    <script>
        $(function () {
            $('#id_born_date, #id_entry_date').datepicker({
                format: 'yyyy-mm-dd',
                language: "zh-CN",
                todayHighlight: true,
                autoclose: true
            });
        })
    </script>
{% endblock %}